version: '3'

services:
  backend.dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      PG_HOST: postgis
      PG_PORT: 5432
      PG_PASSWORD: ${PG_PASSWORD:-geoia}
      PG_USER: ${PG_USER:-geoia}
      PG_DATABASE: ${PG_DATABASE:-geoia-db}
    ports:
      - ${PORT:-3001}:80
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgis
