openapi: 3.0.1
info:
  title: GeoIA Backend
  description: API que descreve as APIs oferecidas pelo serviço
  version: 0.1.0
servers:
  - url: /api/v1
tags:
  - name: Mapas
    description: API para consulta de mapas
  - name: Queimadas
    description: API para consulta de dados de queimadas
  - name: Specification
    description: The swagger API specification
paths:
  /mapas/municipio/{id}:
    get:
      tags:
        - Mapas
      parameters:
        - $ref: '#/components/parameters/municipio_id'
      responses:
        200:
          description: Retorna dados de queimadas do municipio no formato GeoJson
        204:
          description: Não existem dados para a consulta
  /mapas/estado/{id}:
    get:
      tags:
        - Mapas
      parameters:
        - $ref: '#/components/parameters/estado_id'
      responses:
        200:
          description: Retorna dados de queimadas do municipio no formato GeoJson
        204:
          description: Não existem dados para a consulta
  /queimadas/municipios:
    get:
      tags:
        - Queimadas
      responses:
        200:
          description: Retorna os municipios e se estes possuem queimadas
        204:
          description: Não existem dados para a consulta
  /queimadas/estados:
    get:
      tags:
        - Queimadas
      responses:
        200:
          description: Retorna os estados e se estes possuem queimadas
        204:
          description: Não existem dados para a consulta
  /queimadas/municipio/{id}:
    get:
      tags:
        - Queimadas
      parameters:
        - $ref: '#/components/parameters/municipio_id'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/per_page'
        - $ref: '#/components/parameters/detailed'
      responses:
        200:
          description: Retorna dados de queimadas do municipio no formato GeoJson
        204:
          description: Não existem dados para a consulta
  /queimadas/estado/{id}:
    get:
      tags:
        - Queimadas
      parameters:
        - $ref: '#/components/parameters/estado_id'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/per_page'
        - $ref: '#/components/parameters/detailed'
      responses:
        200:
          description: Retorna dados de queimadas do estado no formato GeoJson
        204:
          description: Não existem dados para a consulta
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
components:
  parameters:
    municipio_id:
      in: path
      name: id
      schema:
        type: integer
        example: 5003207
      required: true
    estado_id:
      in: path
      name: id
      schema:
        type: integer
        example: 50
      required: true
    per_page:
      in: query
      name: per_page
      schema:
        type: number
        minimum: 100
        default: 100
      required: false
    page:
      in: query
      name: page
      schema:
        type: number
        minimum: 1
        default: 1
      required: false
    detailed:
      in: query
      name: detailed
      schema:
        type: boolean
        default: false
      required: false
